### ISSUE TITLE
Far Too Many Amount of Client-Side Errors

### ISSUE THREAD

**Issue by sotch-pr35mac** [sotch-pr35mac/skrum#20]
This has to stop, its crashes Chrome Mobile, and its taking far too long to load.

**Comment by steventhanna** [comment]
It must be the theme...

May I refer you to issues #5 and #2 ...

**Comment by steventhanna** [comment]
Hell yeah.  Just crunched that bug. The `pipeline.js` file was bringing all of the js into the `layout.ejs` file.... We both thought we turned that off... But nope.  We only turned it off for CSS... Anyway, we are just going to have to watch the UI, incase things do not work correctly... Its probably because a dependency is missing.
