### ISSUE TITLE
You can only delete the first project listed on the projects page

### ISSUE THREAD

**Issue by steventhanna** [sotch-pr35mac/skrum#37]
For some reason, you can only delete the first project on `projects.ejs` page.  
### Recreate the issue
1. Drop database
2. Lift sails
3. Sign in
4. Create at least 2 projects
5. Attempt to delete any project other than the first one.  Notice that it does not delete
6. Now one would delete the first project to test that the delete function is even working.  Reload the page after clicking the trash can, and the project does appear to be deleted. 
### Another note

If you proceed to delete all of the projects on the `projects.ejs` page, you should notice something odd....
When the system detects that there are no projects, it should bring up a message that says something along the lines of `No Projects`.  Interestingly enough, when you have projects, and then delete them all, the system still thinks that projects exist, because that message does not reappear.  

Perplexing to say the least.

@sotch-pr35mac your input would be appreciated.

**Comment by sotch-pr35mac** [comment]
The buttons don't even make a call to the server because you have them all listed with the same ID, and so only the first element on the page with that ID gets bound to that click listener, so you need to figure out another way to do it, and another way to pass the project id because they all have the project id with a single HTML ID to them, so they need to all have individual IDs associated with them.

**Comment by steventhanna** [comment]
Well thats gay.
